#!/usr/bin/env bash
# Regenerates src/sf-symbols.js — Apple's SF Symbols, rendered by macOS itself
# at 4x into tintable masks, one JS module shared by the Mac and iPhone apps.
#
# ⚠️ WHY MASKS AND NOT SVG. Apple ships the symbols as vector assets inside a
# private bundle, not as a font with public glyph names; the only public way to
# get one out is NSImage(systemSymbolName:), and drawing that into a PDF
# rasterises. A 4x alpha PNG used as a CSS mask, tinted with currentColor, is
# pixel-exact at every size the apps use (17–28pt) on 2x and 3x screens.
#
# ⚠️ LICENSE. SF Symbols may be used only in apps for Apple platforms. The Mac
# app and the iPhone app qualify; the website and the Chrome extension do NOT
# and must keep their own icons. Never import this module from them.
#
#   scripts/sf-symbols.sh          # the phone set → src/sf-symbols.js
#   scripts/sf-symbols.sh mac      # the Mac set   → src/sf-symbols-mac.js
set -euo pipefail
cd "$(dirname "$0")/.."
TMP=$(mktemp -d)
swiftc -O scripts/sf/render.swift -o "$TMP/render" 2>/dev/null
# name:weight — regular unless the HIG uses another for that role
if [ "${1:-}" = mac ]; then
  OUT=src/sf-symbols-mac.js
  # medium: the Mac's line icons are a 2px stroke on a 24 grid, which SF's
  # regular reads thinner than at 16px next to them
  SYMBOLS="cpu:medium arrow.down.to.line:medium sidebar.left:medium gearshape:medium sun.max:medium moon:medium circle.lefthalf.filled:medium plus:semibold arrow.up:semibold sparkles:medium stop.fill:medium xmark:semibold desktopcomputer:medium list.clipboard:medium lock.open:medium bolt:medium lightbulb:medium hand.raised:medium wrench:medium person.2:medium doc.text:medium arrow.triangle.branch:medium folder:medium archivebox:medium tray.and.arrow.up:medium trash:medium mic:medium scope:medium waveform:medium"
else
  OUT=src/sf-symbols.js
  SYMBOLS="gearshape:regular chevron.left:semibold chevron.right:semibold chevron.down:semibold ellipsis.circle:regular arrow.down.circle:regular checkmark:semibold photo:regular arrow.up:semibold stop.fill:regular square.and.pencil:regular info.circle:regular trash:regular xmark:semibold archivebox:regular magnifyingglass:regular camera:regular mic:regular plus:semibold ellipsis:regular"
fi
{
  echo "// GENERATED by scripts/sf-symbols.sh — do not edit. Apple SF Symbols, rendered"
  echo "// by macOS at 4x as alpha masks. Apple-platform apps only (see the script)."
  echo "export const SF_SYMBOLS = {"
  for pair in $SYMBOLS; do
    name=${pair%%:*}; weight=${pair##*:}
    mkdir -p "$TMP/$weight"
    line=$("$TMP/render" "$TMP/$weight" "$weight" 22 "$name")
    pt=$(echo "$line" | sed -E 's/.* ([0-9.]+)x([0-9.]+)pt.*/\1 \2/')
    w=${pt% *}; h=${pt#* }
    b64=$(base64 -i "$TMP/$weight/$name.png" | tr -d '\n')
    echo "  '$name': { w: $w, h: $h, weight: '$weight', src: 'data:image/png;base64,$b64' },"
  done
  echo "}"
} > "$OUT"
rm -rf "$TMP"
echo "$OUT: $(grep -c "src: 'data" "$OUT") symbols, $(du -h "$OUT" | cut -f1)"
